unmemorize/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from todolist.views import Home, AllTasks

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^(?P<category_id>\d+)/', login_required(Home.as_view()), name='index'),
	url(r'^$', login_required(Home.as_view()), name='index'),
	url(r'^accounts/login/', 'todolist.views.display_login', name='display_login'),
	url(r'^authenticate/', 'todolist.views.do_authentication', name='do_authentication'),
	url(r'^logout/', 'todolist.views.do_logout', name='do_logout'),
	url(r'^all/(?P<category_id>\d+)/$', login_required(AllTasks.as_view()), name='all_tasks'),
	url(r'^all/$', login_required(AllTasks.as_view()), name='all_tasks'),
	url(r'^delete/(?P<task_id>\d+)/', 'todolist.views.delete_task', name='delete_task'),
	url(r'^uncomplete/(?P<task_id>\d+)/', 'todolist.views.uncomplete_task', name='uncomplete_task'),
	url(r'^complete/(?P<task_id>\d+)/', 'todolist.views.complete_task', name='complete_task'),
	url(r'^save_task/', 'todolist.views.save_task', name='save_task'),
	url(r'^update_task/(?P<task_id>\d+)/', 'todolist.views.update_task', name='update_task'),
	url(r'^add_category/', 'todolist.views.add_category', name='add_category'),
	url(r'^save_category/', 'todolist.views.save_category', name='save_category'),
	url(r'^modify_category/(?P<category_id>\d+)/', 'todolist.views.modify_category', name='modify_category'),
	url(r'^update_category/', 'todolist.views.update_category', name='update_category'),
	url(r'^delete_category/', 'todolist.views.delete_category', name='delete_category'),
	url(r'^remove_category/', 'todolist.views.remove_category', name='remove_category'),
	(r'^change_password/$', 'django.contrib.auth.views.password_change'),
	url(r'^password/change/done/$',
                    views.password_change_done,
                    name='password_change_done'),
	(r'^password_change_done/$', 'django.contrib.auth.views.password_change_done'),
	# url(r'^unmemorize/', include('unmemorize.foo.urls')),

	# Uncomment the admin/doc line below to enable admin documentation:
	# url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	# url(r'^admin/', include(admin.site.urls)),
)

todolist/models.py
from django.contrib.auth.models import User
from django.db.models import Count
from django.db import models
from django.forms import ModelForm
from todolist.better_models import BetterModel
from todolist.custom_fields import HexadecimalColorField


class HexadecimalColor(BetterModel):
	value = HexadecimalColorField(unique=True)
	
	def __unicode__(self):
		return self.value


class Priority(BetterModel):
	value = models.IntegerField(unique=True)
	color = models.ForeignKey(HexadecimalColor)
	
	def __unicode__(self):
		if self.value > 0:
			return "+" + str(self.value)
		return self.value


class CategoryManager(models.Manager):
	def get_first(self):
		first_category = super(CategoryManager, self).get_query_set().all()[0]
		if not first_category:
			first_category = None
		return first_category


class Category(BetterModel):
	objects = CategoryManager()
	name = models.CharField(unique=True, max_length=30)
	
	def __unicode__(self):
		return self.name


class CategoryForm(ModelForm):
	class Meta:
		model = Category
		fields = ['name']


class TaskManager(models.Manager):
	def get_tasks(self, category_id, completed_tasks):
		return super(TaskManager, self).get_query_set()\
			.select_related()\
			.filter(complete=completed_tasks, category=category_id)\
			.extra(select={'has_due_date': 'due_date IS NOT NULL'})\
			.order_by('-priority__value', '-has_due_date', 'due_date')

	def get_rank_in_list(self, task):
		task_list = self.get_tasks(task.category_id, False)
		current_rank = 1
		for current_task in task_list:
			if current_task == task:
				return current_rank
			current_rank = current_rank + 1
		return 1


class Task(BetterModel):
	objects = TaskManager()
	description = models.CharField(max_length=300)
	note = models.TextField(max_length=2000, null=True, blank=True)
	due_date = models.DateField(null=True, blank=True)
	complete = models.BooleanField(default=False)
	completed_at = models.DateTimeField(null=True, blank=True)
	priority = models.ForeignKey(Priority)
	category = models.ForeignKey(Category)
	
	def __unicode__(self):
		return self.description


class TaskForm(ModelForm):
	class Meta:
		model = Task
		fields = ['description', 'priority', 'category', 'due_date']

	def __init__(self, *args, **kwargs):
		super(TaskForm, self).__init__(*args, **kwargs)
		self.fields['priority'].empty_label = None


class LoginForm(ModelForm):
	class Meta:
		model = User

todolist/views.py
from __future__ import unicode_literals

from django.views.generic.list import ListView
from django.shortcuts import redirect, render
from django.http import Http404, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from todolist.models import Task, TaskForm, TaskManager, Category, CategoryForm, LoginForm
import json

class HomeListView(ListView):
	context_object_name = "tasks"
	template_name = "todolist/tasks_list.html"
	
	def __init__(self, show_completed_tasks):
		super(HomeListView, self).__init__()
		self.show_completed_tasks = show_completed_tasks

	def get_current_category(self):
		if 'category_id' in self.kwargs:
			category = Category.objects.get(pk=self.kwargs['category_id'])
		else:
			category = Category.objects.get_first()
		return category

	def get_queryset(self, **kwargs):
		return Task.objects.get_tasks(self.get_current_category, False)

	def get_context_data(self, **kwargs):
		context = super(HomeListView, self).get_context_data(**kwargs)
		context['new_task_form'] = TaskForm
		context['current_category'] = self.get_current_category
		context['category_list'] = Category.objects.all()
		if self.show_completed_tasks:
			context['complete_tasks'] = Task.objects.get_tasks(self.get_current_category, True)
		return context


class Home(HomeListView):
	def __init__(self):
		super(Home, self).__init__(False)


class AllTasks(HomeListView):
	def __init__(self):
		super(AllTasks, self).__init__(True)


@login_required
def save_task(request):
	form = TaskForm(request.POST)
	if form.is_valid():
		task = form.save()
		if request.is_ajax():
			html = render(request, 'todolist/task/display_task.html', {'task': task})
			response_data = {
				"html": html.content.decode('utf-8'),
				"place": Task.objects.get_rank_in_list(task)
			}
			return HttpResponse(json.dumps(response_data), content_type="application/json")
		return redirect(request.META.get('HTTP_REFERER', 'index'))
	else:
		raise Http404


@login_required
def update_task(request, task_id):
	try:
		task_to_update = Task.objects.get(pk=task_id)
		old_place = Task.objects.get_rank_in_list(task_to_update) + 1
		form = TaskForm(request.POST, instance = task_to_update)
		if form.is_valid():
			form.save()
		else:
			raise Http404
		if request.is_ajax():
			html = render(request, 'todolist/task/display_task.html', {'task': task_to_update})
			response_data = {
				"html": html.content.decode('utf-8'),
				"place": Task.objects.get_rank_in_list(task_to_update),
				"old_place": old_place
			}
			return HttpResponse(json.dumps(response_data), content_type="application/json")
		return redirect(request.META.get('HTTP_REFERER', 'index'))
	except ObjectDoesNotExist:
		raise Http404


@login_required
def uncomplete_task(request, task_id):
	try:
		task_to_complete = Task.objects.get(pk=task_id)
		task_to_complete.complete = False
		task_to_complete.completed_at = timezone.now()
		task_to_complete.save()
		return redirect(request.META.get('HTTP_REFERER', 'index'))
	except ObjectDoesNotExist:
		raise Http404


@login_required
def complete_task(request, task_id):
	try:
		task_to_complete = Task.objects.get(pk=task_id)
		if task_to_complete.complete:
			raise Http404
		task_to_complete.complete = True
		task_to_complete.completed_at = timezone.now()
		task_to_complete.save()
		if request.is_ajax():
			response_data = {
				"completed": True
			}
			return HttpResponse(json.dumps(response_data), content_type="application/json")
		return redirect(request.META.get('HTTP_REFERER', 'index'))
	except ObjectDoesNotExist:
		raise Http404


@login_required
def delete_task(request, task_id):
	try:
		task_to_delete = Task.objects.get(pk=task_id)
		task_to_delete.delete()
		return redirect(request.META.get('HTTP_REFERER', 'index'))
	except ObjectDoesNotExist:
		raise Http404


@login_required
def add_category(request):
	context = {'new_category_form': CategoryForm}
	return render(request, 'todolist/category/add_category.html', context)


@login_required
def save_category(request):
	form = CategoryForm(request.POST)
	if form.is_valid:
		category = form.save()
		if request.is_ajax():
			context = {'category': category}
			html = render(request, 'todolist/category/display_category.html', context)
			response_data = {
				"html": html.content.decode('utf-8')
			}
			return HttpResponse(json.dumps(response_data), content_type="application/json")
		return redirect('index')
	else:
		raise Http404


@login_required
def modify_category(request, category_id):
	category = Category.objects.get(pk=category_id)
	context = {'category': category}
	return render(request, 'todolist/category/modify_category.html', context)


@login_required
def update_category(request):
	try:
		category_id = request.POST.get('id')
		category = Category.objects.get(pk=category_id)
		form = CategoryForm(request.POST, instance = category)
		if form.is_valid():
			form.save()
		else:
			context = {'category_form': form, 'category': category}
			if request.is_ajax():
				html = render(request, 'todolist/category/modify_category.html', context)
				response_data = {
					"html": html.content.decode('utf-8')
				}
				return HttpResponse(json.dumps(response_data), content_type="application/json")
			return render(request, 'todolist/category/modify_category.html', context)
		if request.is_ajax():
			response_data = {
				"new_name": category.name
			}
			return HttpResponse(json.dumps(response_data), content_type="application/json")
		return redirect(request.META.get('HTTP_REFERER', 'index'))
	except ObjectDoesNotExist:
		raise Http404


@login_required
def delete_category(request):
	context = {'category_list': Category.objects.all()}
	return render(request, 'todolist/category/delete_category.html', context)


@login_required
def remove_category(request):
	form = CategoryForm(request.POST)
	if form.is_valid:
		category_id = request.POST.get('category_id')
		category = Category.objects.get(pk=category_id)
		tasks_to_delete = Task.objects.all().filter(category_id=category_id)
		for task in tasks_to_delete:
			task.delete
		category.delete()
		if request.is_ajax():
			response_data = {
				"category_id": category_id
			}
			return HttpResponse(json.dumps(response_data), content_type="application/json")
		return redirect('index')
	else:
		raise Http404


def display_login(request):
	if request.user.is_authenticated():
		return redirect(request.META.get('HTTP_REFERER', 'index'))
	context = {'login_form': LoginForm(request.POST)}
	return render(request, 'todolist/login.html', context)


def do_authentication(request):
	form = LoginForm(request.POST)
	if form.is_valid:
		username = 'user'
		password = request.POST['password']
		user = User.objects.filter(username=username)[:1]
		if user.count() == 0:
			user = User.objects.create_user(username, '', password)
		user = authenticate(username=username, password=password)
		if user is None:
			return display_login(request)
		else:
			if user.is_active:
				login(request, user)
				return redirect('index')
			else:
				return display_login(request)


@login_required
def do_logout(request):
    logout(request)
    return redirect('display_login')

todolist/templates/todolist/task/add_task.html
{% load i18n %}

{% if new_task_form %}
<div class="row-fluid" id="add_task_div">
	<form id="add_task_form" action="{% url 'save_task' %}" method="post">
		{% csrf_token %}
		<div class="span12">
			<table id="add_task_table">
				<tr>
					<td id="add_task_description">
						<input type="text" name="description" maxlength="150" id="id_description" autocomplete="off" placeholder="{% trans "Add task" %}">
					</td>
					<td id="add_task_priority">
						{{ new_task_form.priority }}
					</td>
					<td id="add_task_due_date">
						<input type="text" name="due_date" id="id_due_date" autocomplete="off" placeholder="{% trans "Due date" %}">
					</td>
					<td id="add_task_submit">
						<input id="id_category" type="hidden" name="category" value="{{ current_category.id }}" />
						<input type="submit" class="btn btn-inverse btn-medium" id="add_task_button" value="Add"/>
					</td>
				</tr>
			</table>
		</div>
	</form>
</div>
{% endif %}

todolist/templates/todolist/task/display_completed_task_due_date.html
{% load i18n %}
{% load due_date_extras %}

{% if task.created_at|is_in_current_year %}
	<span class="due_date">{{ task.created_at |date:"d b" }} -<br/>{{ task.completed_at |date:"d b" }}</span>
{% else %}
	<span class="due_date">{{ task.created_at |date:"d b y" }}
		{% if task.completed_at|is_in_current_year %}
			-<br/>{{ task.completed_at |date:"d b" }}
		{% else %}
			-<br/>{{ task.completed_at |date:"d b y" }}
		{% endif %}
	</span>
{% endif %}

todolist/templates/todolist/task/display_task.html
{% load i18n %}

{% if task %}

	{% if task.complete %}
<div class="row-fluid task_div task_div_complete">
	{% else %}
<div class="row-fluid task_div">
	{% endif %}

	<div class="span12">
		<span class="hidden task_id">{{ task.id }}</span>
		<table>
			<tr>
				<td class="task_left_informations">
				{% if task.complete %}
					<a href="{% url 'uncomplete_task' task.id %}">
						<button class="btn btn-warning btn-small">
							<i class="fa fa-undo"></i>
						</button>
					</a>
				{% else %}
					<span href="{% url 'complete_task' task.id %}">
						<button class="btn btn-success btn-small complete_task_button">
							<i class="fa fa-check"></i>
						</button>
					</span>
				{% endif %}
				</td>
				<td class="task_description">
					<div>
					<span class="hidden task_priority_id">{{ task.priority.id }}</span>
					{% if task.priority.value != 0 %}
						<span href="#" class="btn btn-warning btn-mini disabled"
						style="color: #FFFFFF; background-color: #{{ task.priority.color.value }}">
							{{ task.priority }}
						</span>
					{% endif %}
						<span class="task_description">
						{% if task.complete %}
							<strike>
								{{ task }}
							</strike>
						{% else %}
							{{ task }}
						{% endif %}
						</span>
					</div>
				</td>
				<td class="task_due_date">
					{% if task.complete %}
						<span class="hidden task_formatted_due_date">{{ task.due_date|date:'d/m/y' }}</span>
						{% include "todolist/task/display_completed_task_due_date.html" %}
					{% else %}
						<span class="hidden task_formatted_due_date">{{ task.due_date|date:'d/m/y' }}</span>
						{% include "todolist/task/display_task_due_date.html" %}
					{% endif %}
				</td>
			</tr>
		</table>
	</div>
</div>
{% endif %}

todolist/templates/todolist/task/display_task_due_date.html
{% load i18n %}
{% load due_date_extras %}

{% if task.due_date %}
	{% if task.due_date|is_yesterday %}
		<span class="due_date before_today">{% trans "Yesterday" %}</span>
	{% elif task.due_date|comes_in_days:0 %}
		<span class="due_date today_due_date">{% trans "Today" %}</span>
	{% elif task.due_date|comes_in_days:1 %}
		<span class="due_date tomorrow_due_date">{% trans "Tomorrow" %}</span>
	{% elif task.due_date|comes_in_days:2 %}
		{% if task.due_date|is_in_current_year %}
			<span class="due_date in_two_days_due_date">{{ task.due_date |date:"d b" }}</span>
		{% else %}
			<span class="due_date in_two_days_due_date">{{ task.due_date |date:"d b y" }}</span>
		{% endif %}
	{% elif task.due_date|comes_in_days:7 %}
		{% if task.due_date|is_in_current_year %}
			<span class="due_date in_seven_days_due_date">{{ task.due_date |date:"d b" }}</span>
		{% else %}
			<span class="due_date in_seven_days_due_date">{{ task.due_date |date:"d b y" }}</span>
		{% endif %}
	{% elif task.due_date|is_before_today %}
		{% if task.due_date|is_in_current_year %}
			<span class="due_date before_today">{{ task.due_date |date:"d b" }}</span>
		{% else %}
			<span class="due_date before_today">{{ task.due_date |date:"d b y" }}</span>
		{% endif %}
	{% else %}
		{% if task.due_date|is_in_current_year %}
			<span class="due_date">{{ task.due_date |date:"d b" }}</span>
		{% else %}
			<span class="due_date">{{ task.due_date |date:"d b y" }}</span>
		{% endif %}
	{% endif %}
{% endif %}